# Generated by Django 3.0.3 on 2020-02-25 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(blank=True, help_text='<Здесь текст об урл>', max_length=200, null=True)),
                ('lvl', models.IntegerField(default=0, editable=False)),
                ('menu', models.ForeignKey(blank=True, help_text='<Здесь текст о меню>', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_items', to='menu.Menu')),
                ('parent', models.ForeignKey(blank=True, help_text='<Здесь текст о родителе>', null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.MenuItem')),
            ],
        ),
    ]
